### ISSUE TITLE
Fix naming!

### ISSUE THREAD

**Issue by aadrian** [javatuples/javatuples#5]
Hi,

Please fix naming of Tuples to be correct and consistent:
https://en.wikipedia.org/wiki/Tuple

Thank you.

**Comment by danielfernandez** [comment]
Could you please give some detail on why the current class names are not *correct*? I don't see a reason why I could consider a text in a wikipedia page the only source of truth for a topic like this instead of, say, a dictionary.

For instance, *nonuple* isn't even a *noun* at all: http://www.dictionary.com/browse/nonuple?s=t . And anyway, many of the names in that list are primarily used as *adjectives* with a meaning of *"x-fold"*.

Also, how would you design a replacement plan for these classe names without breaking **all** existing user code?

Thank you.

**Comment by aadrian** [comment]
> Could you please give some detail on why the current class names are not correct? 

 - `Unit` tuple contains **0** elements not **1** since it's not a vector.

> I don't see a reason why I could consider a text in a wikipedia page the only source of truth for a topic like this instead of, say, a dictionary.

Have you used a math dictionary?


> Also, how would you design a replacement plan for these classe names without breaking all existing user code?

Deprecate them in the next version, and remove them in the version afterwards? 

Regards.

**Comment by danielfernandez** [comment]
OK, this is enough. I'd please ask you to review your tone and attitude when trying to make suggestions to other people's projects.
